#!/bin/bash

#PBS -N Det1_300000
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=32:mem=900gb

# https://icl-rcs-user-guide.readthedocs.io/en/latest/hpc/pilot/cx3-phase2/#job-sizing-guidance

source ~/anaconda3/etc/profile.d/conda.sh

cd $PBS_O_WORKDIR
steps_folder=300000 # no space
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/3_pmcmc.R" \
    --mode pmcmc2 \
    --n_particles 500 --n_steps "$steps_folder" \
    --run1_stochastic false --run2_stochastic false \
    --ncpus 32 \
    > "$HOME/Strep_postThesis/myresult.txt"

sleep 1
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/4_post_pmcmc_pics.R" \
    --n_steps "$steps_folder"

sleep 1
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/model/sir_stochastic_ageGroup2_2post_pmcmc_picts.R" \
    --n_steps "$steps_folder"

sleep 1
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/5_post_pmcmc_samples_pics.R" \
    --n_steps "$steps_folder"

sleep 1
conda run -n R_envConda Rscript "$HOME/Strep_postThesis/R/6_post_pmcmc_age_validation.R" \
    --n_steps "$steps_folder"

printenv > "$HOME/Strep_postThesis/myenv.txt"